language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script:
  - composer update
  - ./vendor/bin/phing run-all-tests

notifications:
  email: false